/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FixturesResultsRouteImport } from './routes/fixtures-results'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TableRouteImport } from './routes/table'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as PlayersPlayerSlugRouteImport } from './routes/players/$playerSlug'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsTeamSlugRouteImport } from './routes/teams/$teamSlug'
import { Route as TeamsTeamSlugFixturesRouteImport } from './routes/teams/$teamSlug/fixtures'
import { Route as TeamsTeamSlugHistoryRouteImport } from './routes/teams/$teamSlug/history'
import { Route as TeamsTeamSlugResultsRouteImport } from './routes/teams/$teamSlug/results'
import { Route as TeamsTeamSlugSquadRouteImport } from './routes/teams/$teamSlug/squad'
import { Route as TeamsTeamSlugTableRouteImport } from './routes/teams/$teamSlug/table'
import { Route as TeamsTeamSlugTransfersRouteImport } from './routes/teams/$teamSlug/transfers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesResultsRoute = FixturesResultsRouteImport.update({
  id: '/fixtures-results',
  path: '/fixtures-results',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerSlugRoute = PlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamSlugRoute = TeamsTeamSlugRouteImport.update({
  id: '/teams/$teamSlug',
  path: '/teams/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamSlugFixturesRoute = TeamsTeamSlugFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugHistoryRoute = TeamsTeamSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugResultsRoute = TeamsTeamSlugResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugSquadRoute = TeamsTeamSlugSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugTableRoute = TeamsTeamSlugTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugTransfersRoute = TeamsTeamSlugTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fixtures-results': typeof FixturesResultsRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/transfers': typeof TransfersRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamSlug/fixtures': typeof TeamsTeamSlugFixturesRoute
  '/teams/$teamSlug/history': typeof TeamsTeamSlugHistoryRoute
  '/teams/$teamSlug/results': typeof TeamsTeamSlugResultsRoute
  '/teams/$teamSlug/squad': typeof TeamsTeamSlugSquadRoute
  '/teams/$teamSlug/table': typeof TeamsTeamSlugTableRoute
  '/teams/$teamSlug/transfers': typeof TeamsTeamSlugTransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fixtures-results': typeof FixturesResultsRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/transfers': typeof TransfersRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/teams': typeof TeamsIndexRoute
  '/teams/$teamSlug/fixtures': typeof TeamsTeamSlugFixturesRoute
  '/teams/$teamSlug/history': typeof TeamsTeamSlugHistoryRoute
  '/teams/$teamSlug/results': typeof TeamsTeamSlugResultsRoute
  '/teams/$teamSlug/squad': typeof TeamsTeamSlugSquadRoute
  '/teams/$teamSlug/table': typeof TeamsTeamSlugTableRoute
  '/teams/$teamSlug/transfers': typeof TeamsTeamSlugTransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/fixtures-results': typeof FixturesResultsRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/transfers': typeof TransfersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamSlug/fixtures': typeof TeamsTeamSlugFixturesRoute
  '/teams/$teamSlug/history': typeof TeamsTeamSlugHistoryRoute
  '/teams/$teamSlug/results': typeof TeamsTeamSlugResultsRoute
  '/teams/$teamSlug/squad': typeof TeamsTeamSlugSquadRoute
  '/teams/$teamSlug/table': typeof TeamsTeamSlugTableRoute
  '/teams/$teamSlug/transfers': typeof TeamsTeamSlugTransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fixtures-results'
    | '/stats'
    | '/table'
    | '/transfers'
    | '/admin'
    | '/matches/$matchId'
    | '/players/$playerSlug'
    | '/teams/$teamSlug'
    | '/teams/'
    | '/teams/$teamSlug/fixtures'
    | '/teams/$teamSlug/history'
    | '/teams/$teamSlug/results'
    | '/teams/$teamSlug/squad'
    | '/teams/$teamSlug/table'
    | '/teams/$teamSlug/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fixtures-results'
    | '/stats'
    | '/table'
    | '/transfers'
    | '/admin'
    | '/matches/$matchId'
    | '/players/$playerSlug'
    | '/teams/$teamSlug'
    | '/teams'
    | '/teams/$teamSlug/fixtures'
    | '/teams/$teamSlug/history'
    | '/teams/$teamSlug/results'
    | '/teams/$teamSlug/squad'
    | '/teams/$teamSlug/table'
    | '/teams/$teamSlug/transfers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/fixtures-results'
    | '/stats'
    | '/table'
    | '/transfers'
    | '/_authenticated/admin'
    | '/matches/$matchId'
    | '/players/$playerSlug'
    | '/teams/$teamSlug'
    | '/teams/'
    | '/teams/$teamSlug/fixtures'
    | '/teams/$teamSlug/history'
    | '/teams/$teamSlug/results'
    | '/teams/$teamSlug/squad'
    | '/teams/$teamSlug/table'
    | '/teams/$teamSlug/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FixturesResultsRoute: typeof FixturesResultsRoute
  StatsRoute: typeof StatsRoute
  TableRoute: typeof TableRoute
  TransfersRoute: typeof TransfersRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  PlayersPlayerSlugRoute: typeof PlayersPlayerSlugRoute
  TeamsTeamSlugRoute: typeof TeamsTeamSlugRouteWithChildren
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures-results': {
      id: '/fixtures-results'
      path: '/fixtures-results'
      fullPath: '/fixtures-results'
      preLoaderRoute: typeof FixturesResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerSlug': {
      id: '/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PlayersPlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug': {
      id: '/teams/$teamSlug'
      path: '/teams/$teamSlug'
      fullPath: '/teams/$teamSlug'
      preLoaderRoute: typeof TeamsTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug/fixtures': {
      id: '/teams/$teamSlug/fixtures'
      path: '/fixtures'
      fullPath: '/teams/$teamSlug/fixtures'
      preLoaderRoute: typeof TeamsTeamSlugFixturesRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/history': {
      id: '/teams/$teamSlug/history'
      path: '/history'
      fullPath: '/teams/$teamSlug/history'
      preLoaderRoute: typeof TeamsTeamSlugHistoryRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/results': {
      id: '/teams/$teamSlug/results'
      path: '/results'
      fullPath: '/teams/$teamSlug/results'
      preLoaderRoute: typeof TeamsTeamSlugResultsRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/squad': {
      id: '/teams/$teamSlug/squad'
      path: '/squad'
      fullPath: '/teams/$teamSlug/squad'
      preLoaderRoute: typeof TeamsTeamSlugSquadRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/table': {
      id: '/teams/$teamSlug/table'
      path: '/table'
      fullPath: '/teams/$teamSlug/table'
      preLoaderRoute: typeof TeamsTeamSlugTableRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/transfers': {
      id: '/teams/$teamSlug/transfers'
      path: '/transfers'
      fullPath: '/teams/$teamSlug/transfers'
      preLoaderRoute: typeof TeamsTeamSlugTransfersRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TeamsTeamSlugRouteChildren {
  TeamsTeamSlugFixturesRoute: typeof TeamsTeamSlugFixturesRoute
  TeamsTeamSlugHistoryRoute: typeof TeamsTeamSlugHistoryRoute
  TeamsTeamSlugResultsRoute: typeof TeamsTeamSlugResultsRoute
  TeamsTeamSlugSquadRoute: typeof TeamsTeamSlugSquadRoute
  TeamsTeamSlugTableRoute: typeof TeamsTeamSlugTableRoute
  TeamsTeamSlugTransfersRoute: typeof TeamsTeamSlugTransfersRoute
}

const TeamsTeamSlugRouteChildren: TeamsTeamSlugRouteChildren = {
  TeamsTeamSlugFixturesRoute: TeamsTeamSlugFixturesRoute,
  TeamsTeamSlugHistoryRoute: TeamsTeamSlugHistoryRoute,
  TeamsTeamSlugResultsRoute: TeamsTeamSlugResultsRoute,
  TeamsTeamSlugSquadRoute: TeamsTeamSlugSquadRoute,
  TeamsTeamSlugTableRoute: TeamsTeamSlugTableRoute,
  TeamsTeamSlugTransfersRoute: TeamsTeamSlugTransfersRoute,
}

const TeamsTeamSlugRouteWithChildren = TeamsTeamSlugRoute._addFileChildren(
  TeamsTeamSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FixturesResultsRoute: FixturesResultsRoute,
  StatsRoute: StatsRoute,
  TableRoute: TableRoute,
  TransfersRoute: TransfersRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  PlayersPlayerSlugRoute: PlayersPlayerSlugRoute,
  TeamsTeamSlugRoute: TeamsTeamSlugRouteWithChildren,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
