/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FixturesResultsRouteImport } from './routes/fixtures-results'
import { Route as NewsRouteImport } from './routes/news'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TableRouteImport } from './routes/table'
import { Route as TransferRumoursRouteImport } from './routes/transfer-rumours'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as PlayersPlayerSlugRouteImport } from './routes/players/$playerSlug'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsTeamSlugRouteImport } from './routes/teams/$teamSlug'
import { Route as TeamsTeamSlugFixturesRouteImport } from './routes/teams/$teamSlug/fixtures'
import { Route as TeamsTeamSlugResultsRouteImport } from './routes/teams/$teamSlug/results'
import { Route as TeamsTeamSlugSquadRouteImport } from './routes/teams/$teamSlug/squad'
import { Route as TeamsTeamSlugTableRouteImport } from './routes/teams/$teamSlug/table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesResultsRoute = FixturesResultsRouteImport.update({
  id: '/fixtures-results',
  path: '/fixtures-results',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRumoursRoute = TransferRumoursRouteImport.update({
  id: '/transfer-rumours',
  path: '/transfer-rumours',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerSlugRoute = PlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamSlugRoute = TeamsTeamSlugRouteImport.update({
  id: '/teams/$teamSlug',
  path: '/teams/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamSlugFixturesRoute = TeamsTeamSlugFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugResultsRoute = TeamsTeamSlugResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugSquadRoute = TeamsTeamSlugSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugTableRoute = TeamsTeamSlugTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixtures-results': typeof FixturesResultsRoute
  '/news': typeof NewsRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/transfer-rumours': typeof TransferRumoursRoute
  '/transfers': typeof TransfersRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamSlug/fixtures': typeof TeamsTeamSlugFixturesRoute
  '/teams/$teamSlug/results': typeof TeamsTeamSlugResultsRoute
  '/teams/$teamSlug/squad': typeof TeamsTeamSlugSquadRoute
  '/teams/$teamSlug/table': typeof TeamsTeamSlugTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixtures-results': typeof FixturesResultsRoute
  '/news': typeof NewsRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/transfer-rumours': typeof TransferRumoursRoute
  '/transfers': typeof TransfersRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/teams': typeof TeamsIndexRoute
  '/teams/$teamSlug/fixtures': typeof TeamsTeamSlugFixturesRoute
  '/teams/$teamSlug/results': typeof TeamsTeamSlugResultsRoute
  '/teams/$teamSlug/squad': typeof TeamsTeamSlugSquadRoute
  '/teams/$teamSlug/table': typeof TeamsTeamSlugTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fixtures-results': typeof FixturesResultsRoute
  '/news': typeof NewsRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/transfer-rumours': typeof TransferRumoursRoute
  '/transfers': typeof TransfersRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamSlug/fixtures': typeof TeamsTeamSlugFixturesRoute
  '/teams/$teamSlug/results': typeof TeamsTeamSlugResultsRoute
  '/teams/$teamSlug/squad': typeof TeamsTeamSlugSquadRoute
  '/teams/$teamSlug/table': typeof TeamsTeamSlugTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fixtures-results'
    | '/news'
    | '/stats'
    | '/table'
    | '/transfer-rumours'
    | '/transfers'
    | '/matches/$matchId'
    | '/players/$playerSlug'
    | '/teams/$teamSlug'
    | '/teams/'
    | '/teams/$teamSlug/fixtures'
    | '/teams/$teamSlug/results'
    | '/teams/$teamSlug/squad'
    | '/teams/$teamSlug/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fixtures-results'
    | '/news'
    | '/stats'
    | '/table'
    | '/transfer-rumours'
    | '/transfers'
    | '/matches/$matchId'
    | '/players/$playerSlug'
    | '/teams/$teamSlug'
    | '/teams'
    | '/teams/$teamSlug/fixtures'
    | '/teams/$teamSlug/results'
    | '/teams/$teamSlug/squad'
    | '/teams/$teamSlug/table'
  id:
    | '__root__'
    | '/'
    | '/fixtures-results'
    | '/news'
    | '/stats'
    | '/table'
    | '/transfer-rumours'
    | '/transfers'
    | '/matches/$matchId'
    | '/players/$playerSlug'
    | '/teams/$teamSlug'
    | '/teams/'
    | '/teams/$teamSlug/fixtures'
    | '/teams/$teamSlug/results'
    | '/teams/$teamSlug/squad'
    | '/teams/$teamSlug/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixturesResultsRoute: typeof FixturesResultsRoute
  NewsRoute: typeof NewsRoute
  StatsRoute: typeof StatsRoute
  TableRoute: typeof TableRoute
  TransferRumoursRoute: typeof TransferRumoursRoute
  TransfersRoute: typeof TransfersRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  PlayersPlayerSlugRoute: typeof PlayersPlayerSlugRoute
  TeamsTeamSlugRoute: typeof TeamsTeamSlugRouteWithChildren
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures-results': {
      id: '/fixtures-results'
      path: '/fixtures-results'
      fullPath: '/fixtures-results'
      preLoaderRoute: typeof FixturesResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer-rumours': {
      id: '/transfer-rumours'
      path: '/transfer-rumours'
      fullPath: '/transfer-rumours'
      preLoaderRoute: typeof TransferRumoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerSlug': {
      id: '/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PlayersPlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug': {
      id: '/teams/$teamSlug'
      path: '/teams/$teamSlug'
      fullPath: '/teams/$teamSlug'
      preLoaderRoute: typeof TeamsTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug/fixtures': {
      id: '/teams/$teamSlug/fixtures'
      path: '/fixtures'
      fullPath: '/teams/$teamSlug/fixtures'
      preLoaderRoute: typeof TeamsTeamSlugFixturesRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/results': {
      id: '/teams/$teamSlug/results'
      path: '/results'
      fullPath: '/teams/$teamSlug/results'
      preLoaderRoute: typeof TeamsTeamSlugResultsRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/squad': {
      id: '/teams/$teamSlug/squad'
      path: '/squad'
      fullPath: '/teams/$teamSlug/squad'
      preLoaderRoute: typeof TeamsTeamSlugSquadRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/table': {
      id: '/teams/$teamSlug/table'
      path: '/table'
      fullPath: '/teams/$teamSlug/table'
      preLoaderRoute: typeof TeamsTeamSlugTableRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
  }
}

interface TeamsTeamSlugRouteChildren {
  TeamsTeamSlugFixturesRoute: typeof TeamsTeamSlugFixturesRoute
  TeamsTeamSlugResultsRoute: typeof TeamsTeamSlugResultsRoute
  TeamsTeamSlugSquadRoute: typeof TeamsTeamSlugSquadRoute
  TeamsTeamSlugTableRoute: typeof TeamsTeamSlugTableRoute
}

const TeamsTeamSlugRouteChildren: TeamsTeamSlugRouteChildren = {
  TeamsTeamSlugFixturesRoute: TeamsTeamSlugFixturesRoute,
  TeamsTeamSlugResultsRoute: TeamsTeamSlugResultsRoute,
  TeamsTeamSlugSquadRoute: TeamsTeamSlugSquadRoute,
  TeamsTeamSlugTableRoute: TeamsTeamSlugTableRoute,
}

const TeamsTeamSlugRouteWithChildren = TeamsTeamSlugRoute._addFileChildren(
  TeamsTeamSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixturesResultsRoute: FixturesResultsRoute,
  NewsRoute: NewsRoute,
  StatsRoute: StatsRoute,
  TableRoute: TableRoute,
  TransferRumoursRoute: TransferRumoursRoute,
  TransfersRoute: TransfersRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  PlayersPlayerSlugRoute: PlayersPlayerSlugRoute,
  TeamsTeamSlugRoute: TeamsTeamSlugRouteWithChildren,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
